- name: Install PyMySQL
  pip:
    name: pymysql
    state: present
    
- name: create database
  community.mysql.mysql_db:
    login_host: "terraform-20230228091643715500000010.cl0h7nvfyu0t.us-east-1.rds.amazonaws.com" 
    login_user: "benny"
    login_password: "bennypbl"
    name: wordpressdb
    collation: utf8_general_ci
    encoding: utf8
    state: present


- name: Input wordpress credentials
  ansible.builtin.replace:
    path: /var/www/html/wp-config.php 
    regexp: "{{ item.regexp }}"
    replace: "{{ item.line }}"
  loop:
    - { regexp: '^localhost', line: "terraform-20230228091643715500000010.cl0h7nvfyu0t.us-east-1.rds.amazonaws.com" }
    - { regexp: '^username_here', line: "benny" }
    - { regexp: '^database_name_here', line: "wordpressdb" }
    - { regexp: '^password_here', line: "bennypbl" }
